// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mnemo.Data;

#nullable disable

namespace Mnemo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603193138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Correct")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Percent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RepetitionResults");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanSelfAssess")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EasinessFactor")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("LastRepetitionAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("NextRepetitionAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepetitionCounter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepetitionInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VocabularyEntryId")
                        .IsUnique();

                    b.ToTable("RepetitionStates");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionCounter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsessmentEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ElapsedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("task_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RepetitionTasks");

                    b.HasDiscriminator<string>("task_type").HasValue("RepetitionTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mnemo.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Examples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foreign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepetitionResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transcription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Translations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepetitionResultId");

                    b.HasIndex("UserId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.OptionRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("option");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.OrderPartsRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SentenceParts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("parts");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.TextRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.PrimitiveCollection<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("text");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.YesOrNoRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<bool>("CorrectYesOrNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("yesorno");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionState", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.User", "User")
                        .WithMany("RepetitionStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mnemo.Data.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithOne("RepetitionState")
                        .HasForeignKey("Mnemo.Data.Entities.RepetitionState", "VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionTask", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.User", "User")
                        .WithMany("RepetitionTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.RepetitionResult", null)
                        .WithMany("VocabularyEntries")
                        .HasForeignKey("RepetitionResultId");

                    b.HasOne("Mnemo.Data.Entities.User", "User")
                        .WithMany("VocabularyEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionResult", b =>
                {
                    b.Navigation("VocabularyEntries");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.User", b =>
                {
                    b.Navigation("RepetitionStates");

                    b.Navigation("RepetitionTasks");

                    b.Navigation("VocabularyEntries");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.Navigation("RepetitionState");
                });
#pragma warning restore 612, 618
        }
    }
}
