// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mnemo.Data;

#nullable disable

namespace Mnemo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EasinessFactor")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("LastRepetitionAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("NextRepetitionAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepetitionCounter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepetitionInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VocabularyEntryId")
                        .IsUnique();

                    b.ToTable("RepetitionStates", (string)null);
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionCounter")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ElapsedTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntryPartOfSpeech")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("task_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RepetitionTasks", (string)null);

                    b.HasDiscriminator<string>("task_type").HasValue("RepetitionTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mnemo.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Antonyms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnrichmentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foreign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastEnrichmentAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartOfSpeech")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionAudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Translations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Entries", (string)null);
                });

            modelBuilder.Entity("Mnemo.Data.Entities.OptionRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("option");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.SentenceReorderRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentenceParts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("sentence");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.SyllableReorderRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Syllables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("RepetitionTasks", null, t =>
                        {
                            t.Property("CorrectOrder")
                                .HasColumnName("SyllableReorderRepetitionTask_CorrectOrder");
                        });

                    b.HasDiscriminator().HasValue("syllable");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.TextRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("text");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.YesOrNoRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<bool>("CorrectYesOrNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("yesorno");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionState", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.User", null)
                        .WithMany("RepetitionStates")
                        .HasForeignKey("UserId");

                    b.HasOne("Mnemo.Data.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithOne("RepetitionState")
                        .HasForeignKey("Mnemo.Data.Entities.RepetitionState", "VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionTask", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.User", "User")
                        .WithMany("RepetitionTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.User", "User")
                        .WithMany("VocabularyEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.User", b =>
                {
                    b.Navigation("RepetitionStates");

                    b.Navigation("RepetitionTasks");

                    b.Navigation("VocabularyEntries");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.Navigation("RepetitionState");
                });
#pragma warning restore 612, 618
        }
    }
}
