// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mnemo.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mnemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("EasinessFactor")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("LastRepetitionAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NextRepetitionAt")
                        .HasColumnType("date");

                    b.Property<int>("RepetitionCounter")
                        .HasColumnType("integer");

                    b.Property<int>("RepetitionInterval")
                        .HasColumnType("integer");

                    b.Property<int>("VocabularyEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyEntryId")
                        .IsUnique();

                    b.ToTable("RepetitionStates");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionCounter")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("ElapsedTime")
                        .HasColumnType("interval");

                    b.Property<int?>("EntryPartOfSpeech")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VocabularyEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("task_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("RepetitionTasks");

                    b.HasDiscriminator<string>("task_type").HasValue("RepetitionTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mnemo.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("Antonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<int?>("CEFR")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnrichmentStatus")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Examples")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Foreign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastEnrichmentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MergedFromId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("PartOfSpeech")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Synonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Transcription")
                        .HasColumnType("text");

                    b.Property<List<string>>("Translations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MergedFromId");

                    b.HasIndex("OwnerId", "MergedFromId");

                    b.HasIndex("OwnerId", "Foreign", "PartOfSpeech");

                    b.ToTable("VocabularyEntries");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntryLink", b =>
                {
                    b.Property<int>("VocabularyId")
                        .HasColumnType("integer");

                    b.Property<int>("VocabularyEntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VocabularyId", "VocabularyEntryId");

                    b.HasIndex("VocabularyEntryId");

                    b.ToTable("VocabularyEntryLinks");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.OptionRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("option");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.SentenceReorderRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("SentenceParts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("sentence");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.SyllableReorderRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<string>("CorrectOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Syllables")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.ToTable("RepetitionTasks", t =>
                        {
                            t.Property("CorrectOrder")
                                .HasColumnName("SyllableReorderRepetitionTask_CorrectOrder");
                        });

                    b.HasDiscriminator().HasValue("syllable");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.TextRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<List<string>>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("text");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.YesOrNoRepetitionTask", b =>
                {
                    b.HasBaseType("Mnemo.Data.Entities.RepetitionTask");

                    b.Property<bool>("CorrectYesOrNo")
                        .HasColumnType("boolean");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("yesorno");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionState", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithOne("RepetitionState")
                        .HasForeignKey("Mnemo.Data.Entities.RepetitionState", "VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.RepetitionTask", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.User", "Owner")
                        .WithMany("RepetitionTasks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.Vocabulary", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.User", "Owner")
                        .WithMany("Vocabularies")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.Vocabulary", "MergedFrom")
                        .WithMany()
                        .HasForeignKey("MergedFromId");

                    b.HasOne("Mnemo.Data.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergedFrom");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntryLink", b =>
                {
                    b.HasOne("Mnemo.Data.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("VocabularyLinks")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mnemo.Data.Entities.Vocabulary", "Vocabulary")
                        .WithMany("EntryLinks")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.User", b =>
                {
                    b.Navigation("RepetitionTasks");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.Vocabulary", b =>
                {
                    b.Navigation("EntryLinks");
                });

            modelBuilder.Entity("Mnemo.Data.Entities.VocabularyEntry", b =>
                {
                    b.Navigation("RepetitionState");

                    b.Navigation("VocabularyLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
